---
# Basic smartcard enablement task

- name: "Enable smartcard authentication for the IdM Servers"
  hosts: ipaclients
  become: true

  tasks:

    - name: "Load the vault variables"
      when: vault_path is defined
      ansible.builtin.include_vars:
        file: "{{ vault_path }}"

    - name: "Load the other variables"
      when: vars_path is defined
      ansible.builtin.include_vars:
        file: "{{ vars_path }}"

  roles:
    - role: ipasmartcard_client
      state: present # noqa var-naming[no-role-prefix] not a variable
      vars:
        ipaadmin_username: "{{ ipa_principal_username_vault }}" # noqa var-naming[no-role-prefix] these are defined by the freeipa collection
        ipaadmin_password: "{{ ipa_principal_password_vault }}" # noqa var-naming[no-role-prefix]
        ipasmartcard_client_ca_certs: "/etc/ipa/ca.crt" # comma delimited list
